# Déploiement Nginx / php 
# https://www.sitepoint.com/docker-php-development-environment/
version: '3'
services:
    web:
        container_name: gpstracker-nginx
        image: nginx:latest
        ports:
          - "80:80"
          - "443:443"
        volumes:
          - ./docker/conf/nginx.conf:/etc/nginx/conf.d/nginx.conf:ro
          - ./docker/conf/certs:/etc/nginx/certs:ro
          - ./app:/app
        links:
          - "php:gpstracker-php"

    php:
        container_name: gpstracker-php
        build:
            context: .
            dockerfile: php.Dockerfile
        volumes:
            - ./app:/app
        links:
          - "db:gpstracker-mysql"

    mysql:
        container_name: gpstracker-mysql
        environment:
            MARIADB_ROOT_PASSWORD: 'secret'
            MARIADB_USER: 'tracker'
            MARIADB_PASSWORD: 'secret'
            MARIADB_DATABASE: 'gpstracker'
        build:
            context: .
            dockerfile: mariadb.dockerfile
        volumes:
            - ./mysqldata:/var/lib/mysql
            - ./docker/db-init/:/docker-entrypoint-initdb.d/
        ports:
            - 3306:3306
networks:
  gpstracker_network:
    name: gpstracker_network
volumes:
  mysqldata: {}
