# Déploiement Nginx / php /mysql
# https://www.sitepoint.com/docker-php-development-environment/
# https://mindsers.blog/fr/post/configurer-https-nginx-docker-lets-encrypt/

version: '3'

services:
  webserver:
    image: nginx:latest
    ports:
      - 80:80
    #  - 443:443
    restart: always
    volumes:
      - ./docker/nginx/conf/:/etc/nginx/conf.d/:ro
      - .app/public/:/vetc/nginix/html/
      #- ./docker/certbot/www:/var/www/certbot/:ro
      #- ./docker/certbot/conf/:/etc/nginx/ssl/:ro
  #certbot:
  #  image: certbot/certbot:latest
  #  volumes:
  #    - ./docker/certbot/www/:/var/www/certbot/:rw
  #    - ./docker/certbot/conf/:/etc/letsencrypt/:rw
  php:
      build:
          context: .
          dockerfile: php.Dockerfile
      volumes:
          - ./app:/app
  mysql:
      environment:
          MARIADB_ROOT_PASSWORD: 'secret'
          MARIADB_USER: 'tracker'
          MARIADB_PASSWORD: 'secret'
          MARIADB_DATABASE: 'gpstracker'
      build:
          context: .
          dockerfile: mariadb.dockerfile
      volumes:
          - ./mysqldata:/var/lib/mysql
          - ./docker/db-init/:/docker-entrypoint-initdb.d/
      ports:
          - 3306:3306
volumes:
  mysqldata: {}
